export class AddressDepartmentGuatemala {
  departments = {
    'Guatemala': {
      'Guatemala': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 24, 25,],
      'Santa Catarina Pinula': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,],
      'San José Pinula': [],
      'San José del Golfo': [],
      'Palencia': [],
      'Chinautla': [],
      'San Pedro Ayampuc': [],
      'Mixco': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,],
      'San Pedro Sacatepéquez': [1,2,3,4],
      'San Juan Sacatépequez': [1,2,3,4],
      'San Raymundo': [],
      'San Miguel Petapa': [],
      'Chuarrancho': [],
      'Fraijanes': [],
      'Amatitlán': [],
      'Villa Nueva': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      'Villa Canales': [],
      'Petapa': [],
    },
    'El Progreso': {
      'Guastatoya': [],
      'Morazán': [],
      'San Agustín Acasaguastlán': [],
      'San Cristóbal Acasaguastlán': [],
      'El Jícaro': [],
      'Sansare': [],
      'Sanarate': [],
      'San Antonio La Paz': [],
    },
    'Sacatepéquez': {
      'Antigua Guatemala': [],
      'Jocotenango': [],
      'Pastores': [],
      'Sumpango': [],
      'Sto. Domingo Xenacoj': [],
      'Santiago Sacatepéquez': [],
      'San Bartolomé Millpas Altas': [],
      'San Lucas Sacatepéquez': [],
      'Santa Lucia Milpas Altas': [],
      'Magdalena Milpas Altas': [],
      'Santa María de Jesús': [],
      'Ciudad Vieja': [],
      'San Miguel Dueñas': [],
      'Alotenango': [],
      'San Antonio Aguas Calientes': [],
      'Santa Catarina Barahona': [],
    },
    'Chimaltenango': {
      'Chimaltenango': [],
      'San José Poaquil': [],
      'San Martín Jilotepeque': [],
      'Comalapa': [],
      'Santa Apolonia': [],
      'Tecpán Guatemala': [],
      'Patzún': [],
      'Pochuta': [],
      'Patzicia': [],
      'Santa Cruz Balanyá': [],
      'Acatenango': [],
      'Yepocapa': [],
      'San Andrés Iztapa': [],
      'Parramos': [],
      'Zaragoza': [],
      'El Tejar': [],
    },
    'Escuintla': {
      'Escuintla': [],
      'Santa Lucía Cotzumalguapa': [],
      'La Democracia': [],
      'Siquinalá': [],
      'Masagua': [],
      'Tiquisate': [],
      'La Gomera': [],
      'Guanagazapa': [],
      'San José': [],
      'Iztapa': [],
      'Palín': [],
      'San Vicente Pacaya': [],
      'Nueva Concepción': [],
    },
    'Sololá': {
      'Sololá': [],
      'San José Chacayá': [],
      'Santa María Visitación': [],
      'Santa Lucía Utatlán': [],
      'Nahualá': [],
      'Santa Catarina Ixtahuacán': [],
      'Santa Clara La Laguna': [],
      'Concepción': [],
      'San Andrés Semetabaj': [],
      'Panajachel': [],
      'Santa Catarina Palopó': [],
      'San Antonio Palopó': [],
      'San Lucas Tolimán': [],
      'Santa Cruz La Laguna': [],
      'San Pablo La Laguna': [],
      'San Marcos La Laguna': [],
      'San Juan La Laguna': [],
      'San Pedro La Laguna': [],
      'Santiago Atitlán': [],
    },
    'Totonicapán': {
      'Totonicapán': [],
      'San Cristóbal Totonicapán': [],
      'San Francisco El Alto': [],
      'San Andrés Xecul': [],
      'Momostenango': [],
      'Santa María Chiquimula': [],
      'Santa Lucía La Reforma': [],
      'San Bartolo Aguas Calientes': [],
    },
    'Quetzaltenango': {
      'Quetzaltenango': [],
      'Salcajá': [],
      'Olintepeque': [],
      'San Carlos Sija': [],
      'Sibilia': [],
      'Cabricán': [],
      'Cajolá': [],
      'San Miguel Siguilá': [],
      'San Juan Ostuncalco': [],
      'San Mateo': [],
      'Concepción Chiquirichapa': [],
      'San Martín Sacatepéquez': [],
      'Almolonga': [],
      'Cantel': [],
      'Huitán': [],
      'Zunil': [],
      'Colomba': [],
      'San Francisco La Unión': [],
      'El Palmar': [],
      'Coatepeque': [],
      'Génova': [],
      'Flores Costa Cuca': [],
      'La Esperanza': [],
      'Palestina de los Altos': [],
    },
    'Suchitepéquez': {
      'Mazatenango': [],
      'Cuyotenango': [],
      'San Francisco Zapotitlán': [],
      'San Bernardino': [],
      'San José El ídolo': [],
      'Santo Domingo Suchitepéquez': [],
      'San Lorenzo': [],
      'Samayac': [],
      'San Pablo Jocopilas': [],
      'San Antonio Suchitepéquez': [],
      'San Miguel Panán': [],
      'San Gabriel': [],
      'Chicacao': [],
      'Patulul': [],
      'Santa Bárbara': [],
      'San Juan Bautista': [],
      'Santo Tomás La Unión': [],
      'Zunilito': [],
      'Pueblo Nuevo': [],
      'Río Bravo': [],
    },
    'Retalhuleu': {
      'Retalhuleu': [],
      'San Sebastián': [],
      'Santa Cruz Muluá': [],
      'San Martín Zapotitlán': [],
      'San Felipe Retalhuleu': [],
      'San Andrés Villa Seca': [],
      'Champerico': [],
      'Nuevo San Carlos': [],
      'El Asintal': [],
    },
    'San Marcos': {
      'San Marcos': [],
      'San Pedro Sacatepéquez': [],
      'San Antonio Sacatepéquez': [],
      'Comitancillo': [],
      'San Miguel Ixtahuacán': [],
      'Concepción Tutuapa': [],
      'Tacaná': [],
      'Sibinal': [],
      'Tajumulco': [],
      'Tejutla': [],
      'San Rafael Pie de la Cuesta': [],
      'Nuevo Progreso': [],
      'El Tumbador': [],
      'El Rodeo': [],
      'Malacatán': [],
      'Catarina': [],
      'Ayutla': [],
      'Ocós': [],
      'San Pablo': [],
      'El Quetzal': [],
      'La Reforma': [],
      'Pajapita': [],
      'Ixchiguán': [],
      'San José Ojetenam': [],
      'San Cristóbal Cucho': [],
      'Sipacapa': [],
      'Esquipulas Palo Gordo': [],
      'Río Blanco': [],
      'San Lorenzo': [],
    },
    'Huehuetenango': {
      'Huehuetenango': [],
      'Chiantla': [],
      'Malacatancito': [],
      'Cuilco': [],
      'Nentón': [],
      'San Pedro Necta': [],
      'Jacaltenango': [],
      'Soloma': [],
      'San Idelfonso Ixtahuacán': [],
      'Santa Bárbara': [],
      'La Libertad': [],
      'La Democracia': [],
      'San Miguel Acatán': [],
      'San Rafael La Indepencia': [],
      'Todos Santos Cuchumatán': [],
      'San Juan Atitán': [],
      'Santa Eulalia': [],
      'San Mateo Ixtatán': [],
      'Colotenango': [],
      'San Sebastián Huehuetenango': [],
      'Tectitán': [],
      'Concepción Huista': [],
      'San Juan Ixcoy': [],
      'San Antonio Huista': [],
      'San Sebastián Coatán': [],
      'Barillas': [],
      'Aguacatán': [],
      'San Rafael Pétzal': [],
      'San Gaspar Ixchil': [],
      'Santiago Chimaltenango': [],
      'Santa Ana Huista': [],
    },
    'Quiché': {
      'Santa Cruz del Quiché': [],
      'Chiché': [],
      'Chinique': [],
      'Zacualpa': [],
      'Chajul': [],
      'Chichicastenango': [],
      'Patzité': [],
      'San Antonio Ilotenango': [],
      'San Pedro Jocopilas': [],
      'Cunén': [],
      'San Juan Cotzal': [],
      'Joyabaj': [],
      'Nebaj': [],
      'San Andrés Sajcabajá': [],
      'Uspantán': [],
      'Sacapulas': [],
      'San Bartolomé Jocotenango': [],
      'Canillá': [],
      'Chicamán': [],
      'Playa Grande -Ixcán': [],
      'Pachalum': [],
    },
    'Baja Verapaz': {
      'Salamá': [],
      'San Miguel Chicaj': [],
      'Rabinal': [],
      'Cubulco': [],
      'Granados': [],
      'El Chol': [],
      'San Jerónimo': [],
      'Purulhá': [],
    },
    'Alta Verapaz': {
      'Cobán': [],
      'Santa Cruz Verapaz': [],
      'San Cristóbal Verapaz': [],
      'Tactic': [],
      'Tamahú': [],
      'Tucurú': [],
      'Panzós': [],
      'Senahú': [],
      'San Pedro Carchá': [],
      'San Juan Chamelco': [],
      'Lanquín': [],
      'Cahabón': [],
      'Chisec': [],
      'Chahal': [],
      'Fray Bartolomé de las Casas': [],
      'La Tinta': [],
    },
    'Petén': {
      'Flores': [],
      'San José': [],
      'San Benito': [],
      'San Andrés': [],
      'La Libertad': [],
      'San Francisco': [],
      'Santa Ana': [],
      'Dolores': [],
      'San Luis': [],
      'Sayaxché': [],
      'Melchor de Mencos': [],
      'Poptún': [],
    },
    'Izabal': {
      'Puerto Barrios': [],
      'Livingston': [],
      'El Estor': [],
      'Morales': [],
      'Los Amates': [],
    },
    'Zacapa': {
      'Zacapa': [],
      'Estanzuela': [],
      'Río Hondo': [],
      'Gualán': [],
      'Teculután': [],
      'Usumatlán': [],
      'Cabañas': [],
      'San Diego': [],
      'La Unión': [],
      'Huité': [],
    },
    'Chiquimula': {
      'Chiquimula': [],
      'San José La Arada': [],
      'San Juan Ermita': [],
      'Jocotán': [],
      'Camotán': [],
      'Olopa': [],
      'Esquipulas': [],
      'Concepción Las Minas': [],
      'Quetzaltepeque': [],
      'San Jacinto': [],
      'Ipala': [],
    },
    'Jalapa': {
      'Jalapa': [],
      'San Pedro Pinula': [],
      'San Luis Jilotepeque': [],
      'San Manuel Chaparrón': [],
      'San Carlos Alzatate': [],
      'Monjas': [],
      'Mataquescuintla': [],
    },
    'Jutiapa': {
      'Jutiapa': [],
      'El Progreso': [],
      'Santa Catarina Mita': [],
      'Agua Blanca': [],
      'Asunción Mita': [],
      'Yupiltepeque': [],
      'Atescatempa': [],
      'Jerez': [],
      'El Adelanto': [],
      'Zapotitlán': [],
      'Comapa': [],
      'Jalpatagua': [],
      'Conguaco': [],
      'Moyuta': [],
      'Pasaco': [],
      'San José Acatempa': [],
      'Quesada': [],
    },
    'Santa Rosa': {
      'Barberena': [],
      'Casillas': [],
      'Chiquimulilla': [],
      'Cuilapa': [],
      'Guazacapán': [],
      'Nueva Santa Rosa': [],
      'Oratorio': [],
      'Pueblo Nuevo Viñas': [],
      'San Juan Tecuaco': [],
      'San Rafael Las Flores': [],
      'Santa Cruz Naranjo': [],
      'Santa María Ixhuatán': [],
      'Santa Rosa de Lima': [],
      'Taxisco': [],
    }
  };
}
